Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: example.AvailableAppointmentsLambdaRequestHandler
      CodeUri: /Users/frankomlinovic/WebstormProjects/korner/amplify/backend/function/availableAppointments
      Runtime: java11
      Architectures:
        - x86_64