package example;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;

@DynamoDBTable(tableName = "Appointment-yahn64dzuvb4xjqd24ndqxbnzi-staging")
public class Appointment {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate date;
    @DynamoDBAttribute(attributeName = "fieldsID")
    private String fieldsID;
    @DynamoDBAttribute(attributeName = "bookerID")
    private String bookerID;
    @DynamoDBAttribute(attributeName = "confirmed")
    private Boolean confirmed;
    @DynamoDBTypeConverted(converter = LocalTimeConverter.class)
    private LocalTime start;
    @DynamoDBTypeConverted(converter = LocalTimeConverter.class)
    private LocalTime end;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getFieldsID() {
        return fieldsID;
    }

    public void setFieldsID(String fieldsID) {
        this.fieldsID = fieldsID;
    }

    public String getBookerID() {
        return bookerID;
    }

    public void setBookerID(String bookerID) {
        this.bookerID = bookerID;
    }

    public Boolean getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    public LocalTime getStart() {
        return start;
    }

    public void setStart(LocalTime start) {
        this.start = start;
    }

    public LocalTime getEnd() {
        return end;
    }

    public void setEnd(LocalTime end) {
        this.end = end;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
