Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: example.LambdaRequestHandler
      CodeUri: /Users/frankomlinovic/WebstormProjects/korner/amplify/backend/function/confirmAppointment
      Runtime: java11
      Architectures:
        - x86_64